import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.projects': 'Works',
    'nav.courses': 'Courses',
    'nav.blog': 'Blog',
    'nav.contact': 'Say Hello',
    
    // Hero
    'hero.greeting': "Hello, I'm",
    'hero.name': 'Mena Boules',
    'hero.title': 'Award Winning Branding Expert',
    'hero.subtitle': 'Specialize in creating unique visual identities for digital products and believe that a stunning design starts with common values, open communication, and respect for your audience.',
    'hero.cta': 'View Portfolio',
    'hero.contact': 'Get In Touch',
    'hero.tagline': 'Bring your vision to ultimate reality',
    'hero.contentCreator': 'Content Creator',
    'hero.webDeveloper': 'Web Developer',
    'hero.watchVideo': 'Watch Video',
    
    // Services
    'services.title': 'Services',
    'services.subtitle': 'What I can do for you',
    'services.heroTitle': 'My Services',
    'services.heroSubtitle': 'Professional web development and design services tailored to bring your vision to life',
    'services.getQuote': 'Get a Quote',
    'services.inquire': 'Inquire',
    'services.starting': 'Starting',
    'services.readyTitle': 'Ready to Start Your Project?',
    'services.readySubtitle': "Let's discuss your ideas and create something amazing together. Get in touch today!",
    'services.chatWhatsApp': 'Chat on WhatsApp',
    'services.viewWork': 'View My Work',
    'services.uiux.title': 'UI UX Design',
    'services.uiux.desc': 'Crafting modern, user-friendly interfaces and seamless experiences that combine creativity with functionality.',
    'services.webdev.title': 'Web Development',
    'services.webdev.desc': 'Building responsive, high-performance websites using WordPress and other CMS platforms tailored to client needs.',
    'services.custom.title': 'Customization & Maintenance',
    'services.custom.desc': 'Customizing themes, plugins, and delivering ongoing support to ensure smooth and scalable website performance.',
    'services.security.title': 'Problem Solving & Security',
    'services.security.desc': 'Providing solutions for technical issues, performance optimization, and securing websites against vulnerabilities.',
    'services.coding.title': 'Custom Coding & Web Applications',
    'services.coding.desc': 'Developing tailored web applications and private coding solutions to match unique business needs.',
    'services.systems.title': 'Systems & Infrastructure',
    'services.systems.desc': 'Managing systems and servers to ensure reliable performance, scalability, and security.',
    'services.branding.title': 'Brand Identity Design',
    'services.branding.desc': 'Creating unique visual identities that capture the essence of your brand and resonate with your target audience.',
    'services.mobile.title': 'Mobile-First Development',
    'services.mobile.desc': 'Building mobile-optimized websites and progressive web apps that work seamlessly across all devices.',
    
    // About
    'about.title': 'About Me',
    'about.greeting': 'Hi',
    'about.iam': 'I am',
    'about.fullname': 'Mena Boules Fouad',
    'about.description': "I am a dedicated and passionate programmer with over 5 years of experience in the field of Web development. Throughout my career, I have been involved in the development and maintenance of various applications and websites. I possess strong skills in programming languages such as JavaScript and I have the ability to design and implement innovative and efficient software solutions for complex problems.",
    'about.description2': "I am a lifelong learner and am committed to software development principles and best practices. I am a self-driven individual who excels both independently and as part of a team. I take pride in my work and always strive for excellence in everything I do.",
    'about.experience': 'Years Experience',
    'about.projects': 'Projects Completed',
    'about.clients': 'Happy Clients',
    'about.resume': 'View Resume',
    'about.hire': 'Get in Touch',
    
    // Skills
    'skills.title': 'Skills & Technologies',
    'skills.subtitle': 'Technologies I work with',
    
    // Projects
    'projects.title': 'Works',
    'projects.subtitle': 'Explore my creative work',
    'projects.view': 'View Project',
    'projects.code': 'View Code',
    'projects.all': 'All',
    'projects.branding': 'Branding',
    'projects.product': 'Product',
    'projects.websites': 'Websites',
    'projects.uiux': 'UX/UI',
    'projects.apps': 'Applications',
    'projects.preview': 'Live Preview',
    'projects.details': 'View Details',
    'projects.heroTitle': 'My Projects',
    'projects.heroSubtitle': 'Explore my portfolio of web development, UI/UX design, and branding projects',
    'projects.searchPlaceholder': 'Search projects...',
    'projects.allProjects': 'All Projects',
    'projects.productDesign': 'Product Design',
    'projects.uiuxDesign': 'UI/UX Design',
    'projects.noResults': 'No projects found',
    'projects.adjustFilters': 'Try adjusting your search or filter criteria',
    'projects.backToProjects': 'Back to Projects',
    'projects.satisfaction': 'Satisfaction',
    'projects.delivery': 'Delivery',
    'projects.revisions': 'Revisions',
    'projects.included': 'Included',
    'projects.techUsed': 'Technologies Used',
    'projects.startingFrom': 'Starting from',
    'projects.whatsIncluded': "What's Included",
    'projects.similarProjects': 'Similar Projects',
    'projects.requestSimilar': 'Request Similar Project',
    'projects.getQuoteIn24': 'Get a quote within 24 hours',
    'projects.fullName': 'Full Name',
    'projects.phone': 'Phone',
    'projects.budget': 'Budget',
    'projects.selectBudget': 'Select budget',
    'projects.projectDescription': 'Project Description',
    'projects.describePlaceholder': 'Describe your project requirements...',
    'projects.requestQuote': 'Request Quote',
    'projects.sending': 'Sending...',
    'projects.requestSent': 'Request Sent Successfully!',
    'projects.getBackSoon': "We'll get back to you within 24 hours.",
    
    // Courses
    'courses.title': 'My Courses',
    'courses.subtitle': 'Learn from my experience',
    'courses.students': 'Students',
    'courses.hours': 'Hours',
    'courses.lessons': 'Lessons',
    'courses.enroll': 'Enroll Now',
    'courses.preview': 'Preview',
    'courses.allCourses': 'All Courses',
    'courses.pageSubtitle': 'Learn from professional courses and boost your career with practical skills',
    'courses.searchPlaceholder': 'Search courses...',
    'courses.showing': 'Showing',
    'courses.noCourses': 'No courses found',
    'courses.adjustFilters': 'Try adjusting your filters',
    'courses.bestseller': 'BESTSELLER',
    'courses.off': 'OFF',
    'courses.allLevels': 'All Levels',
    'courses.beginner': 'Beginner',
    'courses.intermediate': 'Intermediate',
    'courses.advanced': 'Advanced',
    'courses.backToCourses': 'Back to Courses',
    'courses.reviews': 'reviews',
    'courses.createdBy': 'Created by',
    'courses.lastUpdated': 'Last updated',
    'courses.previewVideo': 'Preview Video',
    'courses.playing': 'Playing...',
    'courses.addToWishlist': 'Add to Wishlist',
    'courses.wishlisted': 'Wishlisted',
    'courses.thisIncludes': 'This course includes:',
    'courses.whatYoullLearn': "What You'll Learn",
    'courses.curriculum': 'Course Curriculum',
    'courses.sections': 'sections',
    'courses.removedFromWishlist': 'Removed from wishlist',
    'courses.addedToWishlist': 'Added to wishlist',
    'courses.redirectingToCheckout': 'Redirecting to checkout...',
    
    // Course Watch
    'courseWatch.lessonOf': 'Lesson',
    'courseWatch.of': 'of',
    'courseWatch.overview': 'Overview',
    'courseWatch.resources': 'Resources',
    'courseWatch.qa': 'Q&A',
    'courseWatch.askQuestion': 'Ask a question about this lesson...',
    'courseWatch.markComplete': 'Mark as Complete',
    'courseWatch.courseContent': 'Course Content',
    'courseWatch.lessonsCompleted': 'lessons completed',
    
    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Insights, tutorials and stories',
    'blog.readMore': 'Read More',
    'blog.backToBlog': 'Back to Blog',
    'blog.minRead': 'min read',
    'blog.share': 'Share',
    'blog.relatedPosts': 'Related Posts',
    'blog.categories': 'Categories',
    'blog.allPosts': 'All Posts',
    'blog.search': 'Search articles...',
    'blog.noResults': 'No articles found',
    'blog.author': 'Author',
    'blog.publishedOn': 'Published on',
    
    // Contact
    'contact.title': "It's time to talk about your project",
    'contact.subtitle': "Let's embark on creative journey together by shaping a visual narrative of your brand in the crowded digital space.",
    'contact.name': 'Your Name',
    'contact.email': 'Your Email',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.phone': 'Phone',
    'contact.whatsapp': 'WhatsApp',
    'contact.address': 'Address',
    
    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.cta': "Let's work together!",
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.backToHome': 'Back to Home',
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signInAccess': 'Sign in to access your account',
    'auth.joinUs': 'Join us to start learning',
    'auth.yourName': 'Your name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signIn': 'Sign In',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.welcome': 'Welcome back!',
    'auth.accountCreated': 'Account created successfully!',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.loginSignup': 'Login / Sign Up',
    'auth.backToLogin': 'Back to Login',
    'auth.forgotPasswordTitle': 'Forgot Password',
    'auth.forgotPasswordSubtitle': 'Enter your email and we\'ll send you a reset link',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.resetEmailSent': 'Reset email sent successfully!',
    'auth.checkEmail': 'Check Your Email',
    'auth.resetEmailSentTo': 'We sent a reset link to',
    'auth.rememberPassword': 'Remember your password?',
    'auth.resetPasswordTitle': 'Reset Password',
    'auth.resetPasswordSubtitle': 'Enter your new password below',
    'auth.newPassword': 'New Password',
    'auth.confirmNewPassword': 'Confirm New Password',
    'auth.passwordRequirements': 'Password must be at least 8 characters',
    'auth.passwordTooShort': 'Password must be at least 8 characters',
    'auth.resetPassword': 'Reset Password',
    'auth.passwordResetSuccess': 'Password Reset Successfully!',
    'auth.canNowLogin': 'You can now login with your new password',
    
    // Certificate
    'certificate.backToProfile': 'Back to Profile',
    'certificate.share': 'Share',
    'certificate.download': 'Download',
    'certificate.downloaded': 'Certificate downloaded!',
    'certificate.downloadError': 'Failed to download certificate',
    'certificate.shareTitle': 'My Certificate',
    'certificate.shareText': 'I completed the course:',
    'certificate.linkCopied': 'Link copied to clipboard!',
    'certificate.certificateOf': 'Certificate of',
    'certificate.completion': 'Completion',
    'certificate.presentedTo': 'This is to certify that',
    'certificate.forCompletion': 'has successfully completed',
    'certificate.hoursOfStudy': 'hours of study',
    'certificate.instructor': 'Instructor',
    'certificate.issueDate': 'Issue Date',
    'certificate.id': 'Certificate ID',
    'certificate.verificationNote': 'This certificate can be verified online using the certificate ID',
    'certificate.print': 'Print',
    'certificate.scanToVerify': 'Scan to Verify',
    
    // Verify Certificate
    'verify.backToHome': 'Back to Home',
    'verify.title': 'Verify Certificate',
    'verify.subtitle': 'Enter a certificate ID to verify its authenticity',
    'verify.certificateId': 'Certificate ID',
    'verify.placeholder': 'Enter certificate ID...',
    'verify.search': 'Verify',
    'verify.example': 'Example',
    'verify.valid': 'Valid Certificate',
    'verify.validDesc': 'This certificate is authentic and verified',
    'verify.invalid': 'Certificate Not Found',
    'verify.invalidDesc': 'We could not find a certificate with this ID',
    'verify.courseName': 'Course Name',
    'verify.studentName': 'Student Name',
    'verify.issueDate': 'Issue Date',
    'verify.completionHours': 'Completion Hours',
    'verify.viewCertificate': 'View Certificate',
    'verify.searchAnother': 'Search Another',
    'verify.checkId': 'Please double-check the certificate ID and try again. Make sure to enter the complete ID including dashes.',
    'verify.tryAgain': 'Try Again',
    'verify.helpText': 'Certificate IDs can be found at the bottom of each certificate issued by our platform.',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.wallet': 'Wallet',
    'profile.wishlist': 'Wishlist',
    'profile.certificates': 'Certificates',
    'profile.myCourses': 'My Courses',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    'profile.backToHome': 'Back to Home',
    'profile.editProfile': 'Edit Profile',
    'profile.saveChanges': 'Save Changes',
    'profile.signOut': 'Sign Out',
    'profile.myWallet': 'My Wallet',
    'profile.availableBalance': 'Available Balance',
    'profile.addFunds': 'Add Funds',
    'profile.addFundsToWallet': 'Add Funds to Wallet',
    'profile.add': 'Add',
    'profile.recentTransactions': 'Recent Transactions',
    'profile.progress': 'Progress',
    'profile.items': 'items',
    'profile.emptyWishlist': 'Your wishlist is empty',
    'profile.browseCourses': 'Browse Courses',
    'profile.buy': 'Buy',
    'profile.earnedOn': 'Earned on',
    'profile.profileUpdated': 'Profile updated successfully!',
    'profile.fundsAdded': 'added to your wallet!',
    'profile.removedFromWishlist': 'Removed from wishlist',
    
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.orderSummary': 'Order Summary',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.wallet': 'Wallet',
    'checkout.instapay': 'InstaPay',
    'checkout.vodafone': 'Vodafone Cash',
    'checkout.confirmPayment': 'Confirm Payment',
    'checkout.transactionRef': 'Transaction Reference',
    'checkout.copyNumber': 'Copy Number',
    'checkout.total': 'Total',
    'checkout.choosePayment': 'Choose a payment method to complete your order.',
    'checkout.back': 'Back',
    'checkout.price': 'Price',
    'checkout.discount': 'Discount',
    'checkout.securePayment': '100% secure encrypted payment',
    'checkout.availableBalance': 'Available balance',
    'checkout.insufficientBalance': 'Insufficient balance',
    'checkout.instantTransfer': 'Instant transfer',
    'checkout.mobileWallet': 'Mobile wallet',
    'checkout.instapaySteps': 'InstaPay steps:',
    'checkout.vodafoneSteps': 'Vodafone Cash steps:',
    'checkout.openBankApp': 'Open your banking app',
    'checkout.chooseInstapay': 'Choose InstaPay transfer',
    'checkout.enterAccount': 'Enter this account:',
    'checkout.openVodafone': 'Open Vodafone Cash',
    'checkout.chooseSendMoney': 'Choose Send Money',
    'checkout.enterNumber': 'Enter this number:',
    'checkout.enterAmount': 'Enter amount:',
    'checkout.enterRefAfter': 'Enter the reference after transfer',
    'checkout.paymentSuccessful': 'Payment successful!',
    'checkout.amountDeducted': 'The amount was deducted from your wallet.',
    'checkout.topUpOrChoose': 'Please top up your wallet or choose another payment method.',
    'checkout.refRequired': 'Transaction reference required',
    'checkout.enterRefVerify': 'Please enter a transaction reference for verification.',
    'checkout.requestSubmitted': 'Request submitted!',
    'checkout.accessActivated': 'Your access will be activated within 24 hours after payment verification.',
    'checkout.copied': 'Copied!',
    'checkout.copiedInstapay': 'Copied InstaPay account',
    'checkout.copiedVodafone': 'Copied Vodafone Cash number',
    'checkout.newBalance': 'New Balance',
    'checkout.afterPurchase': 'After purchase',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.buy': 'Buy',
    'common.free': 'Free',
    'common.all': 'All',
    'common.webDevelopment': 'Web Development',
    'common.design': 'Design',
    'common.cms': 'CMS',
    'common.returnHome': 'Return to Home',
    'common.pageNotFound': 'Page not found',
    'common.oops': 'Oops!',
    'common.responsiveDesign': 'Responsive Design',
    'common.seoOptimized': 'SEO Optimized',
    'common.fastLoading': 'Fast Loading Speed',
    'common.modernUiux': 'Modern UI/UX',
    'common.crossBrowser': 'Cross-Browser Compatible',
    'common.mobileFirst': 'Mobile First Approach',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.about': 'عني',
    'nav.skills': 'المهارات',
    'nav.projects': 'أعمالي',
    'nav.courses': 'الكورسات',
    'nav.blog': 'المدونة',
    'nav.contact': 'تواصل',
    
    // Hero
    'hero.greeting': 'مرحباً، أنا',
    'hero.name': 'مينا بولس',
    'hero.title': 'خبير العلامات التجارية الحائز على جوائز',
    'hero.subtitle': 'متخصص في إنشاء هويات بصرية فريدة للمنتجات الرقمية وأؤمن بأن التصميم المذهل يبدأ بالقيم المشتركة والتواصل المفتوح واحترام جمهورك.',
    'hero.cta': 'شاهد أعمالي',
    'hero.contact': 'تواصل معي',
    'hero.tagline': 'حقق رؤيتك إلى واقع مذهل',
    'hero.contentCreator': 'صانع محتوى',
    'hero.webDeveloper': 'مطور ويب',
    'hero.watchVideo': 'شاهد الفيديو',
    
    // Services
    'services.title': 'الخدمات',
    'services.subtitle': 'ما يمكنني فعله لك',
    'services.heroTitle': 'خدماتي',
    'services.heroSubtitle': 'خدمات تطوير ويب وتصميم احترافية مصممة لتحقيق رؤيتك',
    'services.getQuote': 'احصل على عرض سعر',
    'services.inquire': 'استفسر',
    'services.starting': 'يبدأ من',
    'services.readyTitle': 'مستعد لبدء مشروعك؟',
    'services.readySubtitle': 'دعنا نناقش أفكارك ونخلق شيئاً مذهلاً معاً. تواصل معنا اليوم!',
    'services.chatWhatsApp': 'تواصل عبر واتساب',
    'services.viewWork': 'شاهد أعمالي',
    'services.uiux.title': 'تصميم UI/UX',
    'services.uiux.desc': 'صياغة واجهات حديثة وسهلة الاستخدام وتجارب سلسة تجمع بين الإبداع والوظائف.',
    'services.webdev.title': 'تطوير الويب',
    'services.webdev.desc': 'بناء مواقع ويب متجاوبة وعالية الأداء باستخدام WordPress ومنصات CMS أخرى مصممة حسب احتياجات العميل.',
    'services.custom.title': 'التخصيص والصيانة',
    'services.custom.desc': 'تخصيص القوالب والإضافات وتقديم الدعم المستمر لضمان أداء سلس وقابل للتوسع.',
    'services.security.title': 'حل المشكلات والأمان',
    'services.security.desc': 'تقديم حلول للمشاكل التقنية وتحسين الأداء وتأمين المواقع ضد الثغرات.',
    'services.coding.title': 'برمجة مخصصة وتطبيقات ويب',
    'services.coding.desc': 'تطوير تطبيقات ويب مخصصة وحلول برمجية خاصة لتلبية احتياجات الأعمال الفريدة.',
    'services.systems.title': 'الأنظمة والبنية التحتية',
    'services.systems.desc': 'إدارة الأنظمة والخوادم لضمان الأداء الموثوق والقابلية للتوسع والأمان.',
    'services.branding.title': 'تصميم الهوية البصرية',
    'services.branding.desc': 'إنشاء هويات بصرية فريدة تعكس جوهر علامتك التجارية وتتواصل مع جمهورك المستهدف.',
    'services.mobile.title': 'تطوير متوافق مع الجوال',
    'services.mobile.desc': 'بناء مواقع محسنة للجوال وتطبيقات ويب تقدمية تعمل بسلاسة على جميع الأجهزة.',
    
    // About
    'about.title': 'عني',
    'about.greeting': 'مرحباً',
    'about.iam': 'أنا',
    'about.fullname': 'مينا بولس فؤاد',
    'about.description': 'أنا مبرمج ملتزم وشغوف ولدي أكثر من 5 سنوات من الخبرة في مجال تطوير الويب. خلال مسيرتي المهنية، شاركت في تطوير وصيانة مختلف التطبيقات والمواقع. أمتلك مهارات قوية في لغات البرمجة مثل JavaScript ولدي القدرة على تصميم وتنفيذ حلول برمجية مبتكرة وفعالة للمشاكل المعقدة.',
    'about.description2': 'أنا متعلم مدى الحياة وملتزم بمبادئ تطوير البرمجيات وأفضل الممارسات. أنا شخص يعتمد على الذات ويتفوق سواء بشكل مستقل أو كجزء من فريق. أفتخر بعملي وأسعى دائمًا للتميز في كل ما أقوم به.',
    'about.experience': 'سنوات الخبرة',
    'about.projects': 'مشاريع مكتملة',
    'about.clients': 'عملاء سعداء',
    'about.resume': 'عرض السيرة الذاتية',
    'about.hire': 'تواصل معي',
    
    // Skills
    'skills.title': 'المهارات والتقنيات',
    'skills.subtitle': 'التقنيات التي أعمل بها',
    
    // Projects
    'projects.title': 'أعمالي',
    'projects.subtitle': 'استكشف أعمالي الإبداعية',
    'projects.view': 'عرض المشروع',
    'projects.code': 'عرض الكود',
    'projects.all': 'الكل',
    'projects.branding': 'هوية',
    'projects.product': 'منتجات',
    'projects.websites': 'مواقع',
    'projects.uiux': 'UX/UI',
    'projects.apps': 'تطبيقات',
    'projects.preview': 'معاينة مباشرة',
    'projects.details': 'عرض التفاصيل',
    'projects.heroTitle': 'مشاريعي',
    'projects.heroSubtitle': 'استكشف مجموعة أعمالي في تطوير الويب وتصميم UI/UX والهوية البصرية',
    'projects.searchPlaceholder': 'البحث في المشاريع...',
    'projects.allProjects': 'جميع المشاريع',
    'projects.productDesign': 'تصميم المنتجات',
    'projects.uiuxDesign': 'تصميم UI/UX',
    'projects.noResults': 'لا توجد مشاريع',
    'projects.adjustFilters': 'حاول تعديل معايير البحث أو الفلترة',
    'projects.backToProjects': 'العودة للمشاريع',
    'projects.satisfaction': 'رضا',
    'projects.delivery': 'التسليم',
    'projects.revisions': 'تعديلات',
    'projects.included': 'مشمولة',
    'projects.techUsed': 'التقنيات المستخدمة',
    'projects.startingFrom': 'يبدأ من',
    'projects.whatsIncluded': 'ما المشمول',
    'projects.similarProjects': 'مشاريع مشابهة',
    'projects.requestSimilar': 'اطلب مشروع مشابه',
    'projects.getQuoteIn24': 'احصل على عرض سعر خلال 24 ساعة',
    'projects.fullName': 'الاسم الكامل',
    'projects.phone': 'الهاتف',
    'projects.budget': 'الميزانية',
    'projects.selectBudget': 'اختر الميزانية',
    'projects.projectDescription': 'وصف المشروع',
    'projects.describePlaceholder': 'صف متطلبات مشروعك...',
    'projects.requestQuote': 'اطلب عرض سعر',
    'projects.sending': 'جاري الإرسال...',
    'projects.requestSent': 'تم إرسال الطلب بنجاح!',
    'projects.getBackSoon': 'سنتواصل معك خلال 24 ساعة.',
    
    // Courses
    'courses.title': 'كورساتي',
    'courses.subtitle': 'تعلم من خبرتي',
    'courses.students': 'طالب',
    'courses.hours': 'ساعة',
    'courses.lessons': 'درس',
    'courses.enroll': 'سجل الآن',
    'courses.preview': 'معاينة',
    'courses.allCourses': 'جميع الكورسات',
    'courses.pageSubtitle': 'تعلم من كورسات احترافية وطور مسيرتك المهنية بمهارات عملية',
    'courses.searchPlaceholder': 'البحث في الكورسات...',
    'courses.showing': 'عرض',
    'courses.noCourses': 'لا توجد كورسات',
    'courses.adjustFilters': 'حاول تعديل الفلاتر',
    'courses.bestseller': 'الأكثر مبيعاً',
    'courses.off': 'خصم',
    'courses.allLevels': 'جميع المستويات',
    'courses.beginner': 'مبتدئ',
    'courses.intermediate': 'متوسط',
    'courses.advanced': 'متقدم',
    'courses.backToCourses': 'العودة للكورسات',
    'courses.reviews': 'تقييم',
    'courses.createdBy': 'بواسطة',
    'courses.lastUpdated': 'آخر تحديث',
    'courses.previewVideo': 'فيديو المعاينة',
    'courses.playing': 'جاري التشغيل...',
    'courses.addToWishlist': 'أضف للمفضلة',
    'courses.wishlisted': 'في المفضلة',
    'courses.thisIncludes': 'يشمل هذا الكورس:',
    'courses.whatYoullLearn': 'ما ستتعلمه',
    'courses.curriculum': 'محتوى الكورس',
    'courses.sections': 'أقسام',
    'courses.removedFromWishlist': 'تم الحذف من المفضلة',
    'courses.addedToWishlist': 'تم الإضافة للمفضلة',
    'courses.redirectingToCheckout': 'جاري التوجيه للدفع...',
    
    // Course Watch
    'courseWatch.lessonOf': 'الدرس',
    'courseWatch.of': 'من',
    'courseWatch.overview': 'نظرة عامة',
    'courseWatch.resources': 'الموارد',
    'courseWatch.qa': 'أسئلة وأجوبة',
    'courseWatch.askQuestion': 'اطرح سؤالاً عن هذا الدرس...',
    'courseWatch.markComplete': 'تحديد كمكتمل',
    'courseWatch.courseContent': 'محتوى الكورس',
    'courseWatch.lessonsCompleted': 'دروس مكتملة',
    
    // Blog
    'blog.title': 'المدونة',
    'blog.subtitle': 'رؤى ودروس وقصص',
    'blog.readMore': 'اقرأ المزيد',
    'blog.backToBlog': 'العودة للمدونة',
    'blog.minRead': 'دقيقة قراءة',
    'blog.share': 'مشاركة',
    'blog.relatedPosts': 'مقالات ذات صلة',
    'blog.categories': 'التصنيفات',
    'blog.allPosts': 'جميع المقالات',
    'blog.search': 'البحث في المقالات...',
    'blog.noResults': 'لا توجد مقالات',
    'blog.author': 'الكاتب',
    'blog.publishedOn': 'نُشر في',
    
    // Contact
    'contact.title': 'حان الوقت للحديث عن مشروعك',
    'contact.subtitle': 'لننطلق في رحلة إبداعية معًا من خلال تشكيل سرد بصري لعلامتك التجارية في الفضاء الرقمي المزدحم.',
    'contact.name': 'اسمك',
    'contact.email': 'بريدك الإلكتروني',
    'contact.message': 'رسالتك',
    'contact.send': 'إرسال الرسالة',
    'contact.phone': 'الهاتف',
    'contact.whatsapp': 'واتساب',
    'contact.address': 'العنوان',
    
    // Footer
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.cta': 'لنعمل معًا!',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.name': 'الاسم الكامل',
    'auth.backToHome': 'العودة للرئيسية',
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.createAccount': 'إنشاء حساب',
    'auth.signInAccess': 'سجل دخولك للوصول لحسابك',
    'auth.joinUs': 'انضم إلينا لبدء التعلم',
    'auth.yourName': 'اسمك',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.signIn': 'تسجيل الدخول',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'auth.welcome': 'مرحباً بعودتك!',
    'auth.accountCreated': 'تم إنشاء الحساب بنجاح!',
    'auth.passwordMismatch': 'كلمات المرور غير متطابقة',
    'auth.loginSignup': 'دخول / تسجيل',
    'auth.backToLogin': 'العودة لتسجيل الدخول',
    'auth.forgotPasswordTitle': 'نسيت كلمة المرور',
    'auth.forgotPasswordSubtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين',
    'auth.sendResetLink': 'إرسال رابط إعادة التعيين',
    'auth.resetEmailSent': 'تم إرسال بريد إعادة التعيين بنجاح!',
    'auth.checkEmail': 'تحقق من بريدك الإلكتروني',
    'auth.resetEmailSentTo': 'أرسلنا رابط إعادة التعيين إلى',
    'auth.rememberPassword': 'تذكرت كلمة المرور؟',
    'auth.resetPasswordTitle': 'إعادة تعيين كلمة المرور',
    'auth.resetPasswordSubtitle': 'أدخل كلمة المرور الجديدة أدناه',
    'auth.newPassword': 'كلمة المرور الجديدة',
    'auth.confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
    'auth.passwordRequirements': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    'auth.passwordTooShort': 'كلمة المرور قصيرة جداً (8 أحرف على الأقل)',
    'auth.resetPassword': 'إعادة تعيين كلمة المرور',
    'auth.passwordResetSuccess': 'تم إعادة تعيين كلمة المرور بنجاح!',
    'auth.canNowLogin': 'يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة',
    
    // Certificate
    'certificate.backToProfile': 'العودة للملف الشخصي',
    'certificate.share': 'مشاركة',
    'certificate.download': 'تحميل',
    'certificate.downloaded': 'تم تحميل الشهادة!',
    'certificate.downloadError': 'فشل تحميل الشهادة',
    'certificate.shareTitle': 'شهادتي',
    'certificate.shareText': 'أكملت دورة:',
    'certificate.linkCopied': 'تم نسخ الرابط!',
    'certificate.certificateOf': 'شهادة',
    'certificate.completion': 'إتمام',
    'certificate.presentedTo': 'نشهد بأن',
    'certificate.forCompletion': 'قد أتم بنجاح',
    'certificate.hoursOfStudy': 'ساعة دراسية',
    'certificate.instructor': 'المدرب',
    'certificate.issueDate': 'تاريخ الإصدار',
    'certificate.id': 'رقم الشهادة',
    'certificate.verificationNote': 'يمكن التحقق من هذه الشهادة عبر الإنترنت باستخدام رقم الشهادة',
    'certificate.print': 'طباعة',
    'certificate.scanToVerify': 'امسح للتحقق',
    
    // Verify Certificate
    'verify.backToHome': 'العودة للرئيسية',
    'verify.title': 'التحقق من الشهادة',
    'verify.subtitle': 'أدخل رقم الشهادة للتحقق من صحتها',
    'verify.certificateId': 'رقم الشهادة',
    'verify.placeholder': 'أدخل رقم الشهادة...',
    'verify.search': 'تحقق',
    'verify.example': 'مثال',
    'verify.valid': 'شهادة صالحة',
    'verify.validDesc': 'هذه الشهادة موثقة ومعتمدة',
    'verify.invalid': 'الشهادة غير موجودة',
    'verify.invalidDesc': 'لم نتمكن من العثور على شهادة بهذا الرقم',
    'verify.courseName': 'اسم الكورس',
    'verify.studentName': 'اسم الطالب',
    'verify.issueDate': 'تاريخ الإصدار',
    'verify.completionHours': 'ساعات الإتمام',
    'verify.viewCertificate': 'عرض الشهادة',
    'verify.searchAnother': 'البحث عن أخرى',
    'verify.checkId': 'يرجى التأكد من رقم الشهادة والمحاولة مرة أخرى. تأكد من إدخال الرقم الكامل بما في ذلك الشرطات.',
    'verify.tryAgain': 'حاول مرة أخرى',
    'verify.helpText': 'يمكن العثور على أرقام الشهادات في أسفل كل شهادة صادرة من منصتنا.',
    
    // Profile
    'profile.title': 'ملفي الشخصي',
    'profile.wallet': 'المحفظة',
    'profile.wishlist': 'المفضلة',
    'profile.certificates': 'الشهادات',
    'profile.myCourses': 'كورساتي',
    'profile.settings': 'الإعدادات',
    'profile.logout': 'تسجيل الخروج',
    'profile.backToHome': 'العودة للرئيسية',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.signOut': 'تسجيل الخروج',
    'profile.myWallet': 'محفظتي',
    'profile.availableBalance': 'الرصيد المتاح',
    'profile.addFunds': 'إضافة رصيد',
    'profile.addFundsToWallet': 'إضافة رصيد للمحفظة',
    'profile.add': 'إضافة',
    'profile.recentTransactions': 'المعاملات الأخيرة',
    'profile.progress': 'التقدم',
    'profile.items': 'عناصر',
    'profile.emptyWishlist': 'قائمة المفضلة فارغة',
    'profile.browseCourses': 'تصفح الكورسات',
    'profile.buy': 'شراء',
    'profile.earnedOn': 'حصلت عليها في',
    'profile.profileUpdated': 'تم تحديث الملف الشخصي بنجاح!',
    'profile.fundsAdded': 'تمت إضافتها لمحفظتك!',
    'profile.removedFromWishlist': 'تم الحذف من المفضلة',
    
    // Checkout
    'checkout.title': 'إتمام الشراء',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.wallet': 'المحفظة',
    'checkout.instapay': 'إنستا باي',
    'checkout.vodafone': 'فودافون كاش',
    'checkout.confirmPayment': 'تأكيد الدفع',
    'checkout.transactionRef': 'رقم المعاملة',
    'checkout.copyNumber': 'نسخ الرقم',
    'checkout.total': 'الإجمالي',
    'checkout.choosePayment': 'اختر طريقة الدفع لإتمام طلبك.',
    'checkout.back': 'رجوع',
    'checkout.price': 'السعر',
    'checkout.discount': 'الخصم',
    'checkout.securePayment': 'دفع آمن ومشفر 100%',
    'checkout.availableBalance': 'الرصيد المتاح',
    'checkout.insufficientBalance': 'رصيد غير كافي',
    'checkout.instantTransfer': 'تحويل فوري',
    'checkout.mobileWallet': 'محفظة إلكترونية',
    'checkout.instapaySteps': 'خطوات الدفع عبر انستا باي:',
    'checkout.vodafoneSteps': 'خطوات الدفع عبر فودافون كاش:',
    'checkout.openBankApp': 'افتح تطبيق البنك الخاص بك',
    'checkout.chooseInstapay': 'اختر التحويل عبر انستا باي',
    'checkout.enterAccount': 'أدخل الحساب التالي:',
    'checkout.openVodafone': 'افتح تطبيق فودافون كاش',
    'checkout.chooseSendMoney': 'اختر تحويل أموال',
    'checkout.enterNumber': 'أدخل الرقم التالي:',
    'checkout.enterAmount': 'أدخل المبلغ:',
    'checkout.enterRefAfter': 'أدخل رقم العملية بعد التحويل',
    'checkout.paymentSuccessful': 'تم الدفع بنجاح!',
    'checkout.amountDeducted': 'تم خصم المبلغ من محفظتك.',
    'checkout.topUpOrChoose': 'يرجى شحن المحفظة أو اختيار طريقة دفع أخرى.',
    'checkout.refRequired': 'مطلوب رقم العملية',
    'checkout.enterRefVerify': 'يرجى إدخال رقم العملية/المرجع للتحقق.',
    'checkout.requestSubmitted': 'تم إرسال طلبك!',
    'checkout.accessActivated': 'سيتم تفعيل الكورس خلال 24 ساعة بعد التحقق من الدفع.',
    'checkout.copied': 'تم النسخ!',
    'checkout.copiedInstapay': 'تم نسخ حساب انستا باي',
    'checkout.copiedVodafone': 'تم نسخ رقم فودافون كاش',
    'checkout.newBalance': 'الرصيد الجديد',
    'checkout.afterPurchase': 'بعد الشراء',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.buy': 'شراء',
    'common.free': 'مجاني',
    'common.all': 'الكل',
    'common.webDevelopment': 'تطوير الويب',
    'common.design': 'تصميم',
    'common.cms': 'CMS',
    'common.returnHome': 'العودة للرئيسية',
    'common.pageNotFound': 'الصفحة غير موجودة',
    'common.oops': 'عفواً!',
    'common.responsiveDesign': 'تصميم متجاوب',
    'common.seoOptimized': 'محسن لمحركات البحث',
    'common.fastLoading': 'سرعة تحميل عالية',
    'common.modernUiux': 'تصميم UI/UX حديث',
    'common.crossBrowser': 'متوافق مع جميع المتصفحات',
    'common.mobileFirst': 'أولوية للجوال',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.services': 'Dienstleistungen',
    'nav.about': 'Über mich',
    'nav.skills': 'Fähigkeiten',
    'nav.projects': 'Arbeiten',
    'nav.courses': 'Kurse',
    'nav.blog': 'Blog',
    'nav.contact': 'Kontakt',
    
    // Hero
    'hero.greeting': 'Hallo, ich bin',
    'hero.name': 'Mena Boules',
    'hero.title': 'Preisgekrönter Branding-Experte',
    'hero.subtitle': 'Spezialisiert auf die Erstellung einzigartiger visueller Identitäten für digitale Produkte. Ich glaube, dass großartiges Design mit gemeinsamen Werten, offener Kommunikation und Respekt für Ihr Publikum beginnt.',
    'hero.cta': 'Portfolio ansehen',
    'hero.contact': 'Kontakt aufnehmen',
    'hero.tagline': 'Verwirklichen Sie Ihre Vision zur ultimativen Realität',
    'hero.contentCreator': 'Content Creator',
    'hero.webDeveloper': 'Webentwickler',
    'hero.watchVideo': 'Video ansehen',
    
    // Services
    'services.title': 'Dienstleistungen',
    'services.subtitle': 'Was ich für Sie tun kann',
    'services.heroTitle': 'Meine Dienstleistungen',
    'services.heroSubtitle': 'Professionelle Webentwicklung und Designdienstleistungen, maßgeschneidert um Ihre Vision zum Leben zu erwecken',
    'services.getQuote': 'Angebot anfordern',
    'services.inquire': 'Anfragen',
    'services.starting': 'Ab',
    'services.readyTitle': 'Bereit, Ihr Projekt zu starten?',
    'services.readySubtitle': 'Lassen Sie uns Ihre Ideen besprechen und gemeinsam etwas Erstaunliches erschaffen. Kontaktieren Sie uns noch heute!',
    'services.chatWhatsApp': 'Chat auf WhatsApp',
    'services.viewWork': 'Meine Arbeit ansehen',
    'services.uiux.title': 'UI/UX Design',
    'services.uiux.desc': 'Gestaltung moderner, benutzerfreundlicher Oberflächen und nahtloser Erlebnisse, die Kreativität mit Funktionalität verbinden.',
    'services.webdev.title': 'Webentwicklung',
    'services.webdev.desc': 'Erstellung responsiver, leistungsstarker Websites mit WordPress und anderen CMS-Plattformen, maßgeschneidert auf Kundenbedürfnisse.',
    'services.custom.title': 'Anpassung & Wartung',
    'services.custom.desc': 'Anpassung von Themes, Plugins und kontinuierlicher Support für reibungslose und skalierbare Website-Leistung.',
    'services.security.title': 'Problemlösung & Sicherheit',
    'services.security.desc': 'Lösungen für technische Probleme, Leistungsoptimierung und Absicherung von Websites gegen Schwachstellen.',
    'services.coding.title': 'Individuelle Programmierung & Web-Apps',
    'services.coding.desc': 'Entwicklung maßgeschneiderter Webanwendungen und privater Programmierlösungen für einzigartige Geschäftsanforderungen.',
    'services.systems.title': 'Systeme & Infrastruktur',
    'services.systems.desc': 'Verwaltung von Systemen und Servern für zuverlässige Leistung, Skalierbarkeit und Sicherheit.',
    'services.branding.title': 'Markenidentitätsdesign',
    'services.branding.desc': 'Erstellung einzigartiger visueller Identitäten, die das Wesen Ihrer Marke einfangen und mit Ihrer Zielgruppe resonieren.',
    'services.mobile.title': 'Mobile-First-Entwicklung',
    'services.mobile.desc': 'Erstellung mobiloptimierter Websites und progressiver Web-Apps, die nahtlos auf allen Geräten funktionieren.',
    
    // About
    'about.title': 'Über mich',
    'about.greeting': 'Hallo',
    'about.iam': 'Ich bin',
    'about.fullname': 'Mena Boules Fouad',
    'about.description': 'Ich bin ein engagierter und leidenschaftlicher Programmierer mit über 5 Jahren Erfahrung in der Webentwicklung. Im Laufe meiner Karriere war ich an der Entwicklung und Wartung verschiedener Anwendungen und Websites beteiligt. Ich verfüge über starke Fähigkeiten in Programmiersprachen wie JavaScript und bin in der Lage, innovative und effiziente Softwarelösungen für komplexe Probleme zu entwerfen und umzusetzen.',
    'about.description2': 'Ich lerne lebenslang und bin den Prinzipien der Softwareentwicklung und Best Practices verpflichtet. Ich bin eine selbstständige Person, die sowohl unabhängig als auch im Team hervorragende Leistungen erbringt. Ich bin stolz auf meine Arbeit und strebe stets nach Exzellenz in allem, was ich tue.',
    'about.experience': 'Jahre Erfahrung',
    'about.projects': 'Abgeschlossene Projekte',
    'about.clients': 'Zufriedene Kunden',
    'about.resume': 'Lebenslauf ansehen',
    'about.hire': 'Kontakt aufnehmen',
    
    // Skills
    'skills.title': 'Fähigkeiten & Technologien',
    'skills.subtitle': 'Technologien, mit denen ich arbeite',
    
    // Projects
    'projects.title': 'Arbeiten',
    'projects.subtitle': 'Entdecken Sie meine kreativen Arbeiten',
    'projects.view': 'Projekt ansehen',
    'projects.code': 'Code ansehen',
    'projects.all': 'Alle',
    'projects.branding': 'Branding',
    'projects.product': 'Produkt',
    'projects.websites': 'Websites',
    'projects.uiux': 'UX/UI',
    'projects.apps': 'Anwendungen',
    'projects.preview': 'Live-Vorschau',
    'projects.details': 'Details ansehen',
    'projects.heroTitle': 'Meine Projekte',
    'projects.heroSubtitle': 'Entdecken Sie mein Portfolio für Webentwicklung, UI/UX-Design und Branding-Projekte',
    'projects.searchPlaceholder': 'Projekte suchen...',
    'projects.allProjects': 'Alle Projekte',
    'projects.productDesign': 'Produktdesign',
    'projects.uiuxDesign': 'UI/UX-Design',
    'projects.noResults': 'Keine Projekte gefunden',
    'projects.adjustFilters': 'Versuchen Sie, Ihre Such- oder Filterkriterien anzupassen',
    'projects.backToProjects': 'Zurück zu Projekte',
    'projects.satisfaction': 'Zufriedenheit',
    'projects.delivery': 'Lieferung',
    'projects.revisions': 'Revisionen',
    'projects.included': 'Inklusive',
    'projects.techUsed': 'Verwendete Technologien',
    'projects.startingFrom': 'Ab',
    'projects.whatsIncluded': 'Was enthalten ist',
    'projects.similarProjects': 'Ähnliche Projekte',
    'projects.requestSimilar': 'Ähnliches Projekt anfragen',
    'projects.getQuoteIn24': 'Angebot innerhalb von 24 Stunden erhalten',
    'projects.fullName': 'Vollständiger Name',
    'projects.phone': 'Telefon',
    'projects.budget': 'Budget',
    'projects.selectBudget': 'Budget auswählen',
    'projects.projectDescription': 'Projektbeschreibung',
    'projects.describePlaceholder': 'Beschreiben Sie Ihre Projektanforderungen...',
    'projects.requestQuote': 'Angebot anfordern',
    'projects.sending': 'Wird gesendet...',
    'projects.requestSent': 'Anfrage erfolgreich gesendet!',
    'projects.getBackSoon': 'Wir melden uns innerhalb von 24 Stunden bei Ihnen.',
    
    // Courses
    'courses.title': 'Meine Kurse',
    'courses.subtitle': 'Lernen Sie aus meiner Erfahrung',
    'courses.students': 'Studenten',
    'courses.hours': 'Stunden',
    'courses.lessons': 'Lektionen',
    'courses.enroll': 'Jetzt anmelden',
    'courses.preview': 'Vorschau',
    'courses.allCourses': 'Alle Kurse',
    'courses.pageSubtitle': 'Lernen Sie von professionellen Kursen und fördern Sie Ihre Karriere mit praktischen Fähigkeiten',
    'courses.searchPlaceholder': 'Kurse suchen...',
    'courses.showing': 'Zeige',
    'courses.noCourses': 'Keine Kurse gefunden',
    'courses.adjustFilters': 'Versuchen Sie, Ihre Filter anzupassen',
    'courses.bestseller': 'BESTSELLER',
    'courses.off': 'RABATT',
    'courses.allLevels': 'Alle Stufen',
    'courses.beginner': 'Anfänger',
    'courses.intermediate': 'Mittelstufe',
    'courses.advanced': 'Fortgeschritten',
    'courses.backToCourses': 'Zurück zu Kurse',
    'courses.reviews': 'Bewertungen',
    'courses.createdBy': 'Erstellt von',
    'courses.lastUpdated': 'Zuletzt aktualisiert',
    'courses.previewVideo': 'Vorschau-Video',
    'courses.playing': 'Wird abgespielt...',
    'courses.addToWishlist': 'Zur Wunschliste',
    'courses.wishlisted': 'Auf Wunschliste',
    'courses.thisIncludes': 'Dieser Kurs enthält:',
    'courses.whatYoullLearn': 'Was Sie lernen werden',
    'courses.curriculum': 'Kursinhalt',
    'courses.sections': 'Abschnitte',
    'courses.removedFromWishlist': 'Von Wunschliste entfernt',
    'courses.addedToWishlist': 'Zur Wunschliste hinzugefügt',
    'courses.redirectingToCheckout': 'Weiterleitung zur Kasse...',
    
    // Course Watch
    'courseWatch.lessonOf': 'Lektion',
    'courseWatch.of': 'von',
    'courseWatch.overview': 'Übersicht',
    'courseWatch.resources': 'Ressourcen',
    'courseWatch.qa': 'Fragen & Antworten',
    'courseWatch.askQuestion': 'Stellen Sie eine Frage zu dieser Lektion...',
    'courseWatch.markComplete': 'Als abgeschlossen markieren',
    'courseWatch.courseContent': 'Kursinhalt',
    'courseWatch.lessonsCompleted': 'Lektionen abgeschlossen',
    
    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Einblicke, Tutorials und Geschichten',
    'blog.readMore': 'Weiterlesen',
    'blog.backToBlog': 'Zurück zum Blog',
    'blog.minRead': 'Min. Lesezeit',
    'blog.share': 'Teilen',
    'blog.relatedPosts': 'Ähnliche Beiträge',
    'blog.categories': 'Kategorien',
    'blog.allPosts': 'Alle Beiträge',
    'blog.search': 'Artikel suchen...',
    'blog.noResults': 'Keine Artikel gefunden',
    'blog.author': 'Autor',
    'blog.publishedOn': 'Veröffentlicht am',
    
    // Contact
    'contact.title': 'Zeit, über Ihr Projekt zu sprechen',
    'contact.subtitle': 'Lassen Sie uns gemeinsam eine kreative Reise beginnen, indem wir eine visuelle Geschichte Ihrer Marke im überfüllten digitalen Raum gestalten.',
    'contact.name': 'Ihr Name',
    'contact.email': 'Ihre E-Mail',
    'contact.message': 'Ihre Nachricht',
    'contact.send': 'Nachricht senden',
    'contact.phone': 'Telefon',
    'contact.whatsapp': 'WhatsApp',
    'contact.address': 'Adresse',
    
    // Footer
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.cta': 'Lass uns zusammenarbeiten!',
    
    // Auth
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.name': 'Vollständiger Name',
    'auth.backToHome': 'Zurück zur Startseite',
    'auth.welcomeBack': 'Willkommen zurück',
    'auth.createAccount': 'Konto erstellen',
    'auth.signInAccess': 'Melden Sie sich an, um auf Ihr Konto zuzugreifen',
    'auth.joinUs': 'Treten Sie bei, um mit dem Lernen zu beginnen',
    'auth.yourName': 'Ihr Name',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.signIn': 'Anmelden',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.haveAccount': 'Bereits ein Konto?',
    'auth.welcome': 'Willkommen zurück!',
    'auth.accountCreated': 'Konto erfolgreich erstellt!',
    'auth.passwordMismatch': 'Passwörter stimmen nicht überein',
    'auth.loginSignup': 'Anmelden / Registrieren',
    'auth.backToLogin': 'Zurück zur Anmeldung',
    'auth.forgotPasswordTitle': 'Passwort vergessen',
    'auth.forgotPasswordSubtitle': 'Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Reset-Link',
    'auth.sendResetLink': 'Reset-Link senden',
    'auth.resetEmailSent': 'Reset-E-Mail erfolgreich gesendet!',
    'auth.checkEmail': 'Überprüfen Sie Ihre E-Mail',
    'auth.resetEmailSentTo': 'Wir haben einen Reset-Link gesendet an',
    'auth.rememberPassword': 'Passwort erinnert?',
    'auth.resetPasswordTitle': 'Passwort zurücksetzen',
    'auth.resetPasswordSubtitle': 'Geben Sie unten Ihr neues Passwort ein',
    'auth.newPassword': 'Neues Passwort',
    'auth.confirmNewPassword': 'Neues Passwort bestätigen',
    'auth.passwordRequirements': 'Passwort muss mindestens 8 Zeichen haben',
    'auth.passwordTooShort': 'Passwort ist zu kurz (mindestens 8 Zeichen)',
    'auth.resetPassword': 'Passwort zurücksetzen',
    'auth.passwordResetSuccess': 'Passwort erfolgreich zurückgesetzt!',
    'auth.canNowLogin': 'Sie können sich jetzt mit Ihrem neuen Passwort anmelden',
    
    // Certificate
    'certificate.backToProfile': 'Zurück zum Profil',
    'certificate.share': 'Teilen',
    'certificate.download': 'Herunterladen',
    'certificate.downloaded': 'Zertifikat heruntergeladen!',
    'certificate.downloadError': 'Fehler beim Herunterladen',
    'certificate.shareTitle': 'Mein Zertifikat',
    'certificate.shareText': 'Ich habe den Kurs abgeschlossen:',
    'certificate.linkCopied': 'Link kopiert!',
    'certificate.certificateOf': 'Zertifikat über',
    'certificate.completion': 'Abschluss',
    'certificate.presentedTo': 'Hiermit wird bestätigt, dass',
    'certificate.forCompletion': 'erfolgreich abgeschlossen hat',
    'certificate.hoursOfStudy': 'Stunden Studium',
    'certificate.instructor': 'Kursleiter',
    'certificate.issueDate': 'Ausstellungsdatum',
    'certificate.id': 'Zertifikat-ID',
    'certificate.verificationNote': 'Dieses Zertifikat kann online mit der Zertifikat-ID überprüft werden',
    'certificate.print': 'Drucken',
    'certificate.scanToVerify': 'Scannen zum Verifizieren',
    
    // Verify Certificate
    'verify.backToHome': 'Zurück zur Startseite',
    'verify.title': 'Zertifikat überprüfen',
    'verify.subtitle': 'Geben Sie eine Zertifikat-ID ein, um die Echtheit zu überprüfen',
    'verify.certificateId': 'Zertifikat-ID',
    'verify.placeholder': 'Zertifikat-ID eingeben...',
    'verify.search': 'Überprüfen',
    'verify.example': 'Beispiel',
    'verify.valid': 'Gültiges Zertifikat',
    'verify.validDesc': 'Dieses Zertifikat ist authentisch und verifiziert',
    'verify.invalid': 'Zertifikat nicht gefunden',
    'verify.invalidDesc': 'Wir konnten kein Zertifikat mit dieser ID finden',
    'verify.courseName': 'Kursname',
    'verify.studentName': 'Studentenname',
    'verify.issueDate': 'Ausstellungsdatum',
    'verify.completionHours': 'Abschlussstunden',
    'verify.viewCertificate': 'Zertifikat anzeigen',
    'verify.searchAnother': 'Andere suchen',
    'verify.checkId': 'Bitte überprüfen Sie die Zertifikat-ID und versuchen Sie es erneut. Stellen Sie sicher, dass Sie die vollständige ID einschließlich Bindestrichen eingeben.',
    'verify.tryAgain': 'Erneut versuchen',
    'verify.helpText': 'Zertifikat-IDs finden Sie am unteren Rand jedes von unserer Plattform ausgestellten Zertifikats.',
    
    // Profile
    'profile.title': 'Mein Profil',
    'profile.wallet': 'Geldbörse',
    'profile.wishlist': 'Wunschliste',
    'profile.certificates': 'Zertifikate',
    'profile.myCourses': 'Meine Kurse',
    'profile.settings': 'Einstellungen',
    'profile.logout': 'Abmelden',
    'profile.backToHome': 'Zurück zur Startseite',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.saveChanges': 'Änderungen speichern',
    'profile.signOut': 'Abmelden',
    'profile.myWallet': 'Meine Geldbörse',
    'profile.availableBalance': 'Verfügbares Guthaben',
    'profile.addFunds': 'Guthaben aufladen',
    'profile.addFundsToWallet': 'Guthaben zur Geldbörse hinzufügen',
    'profile.add': 'Hinzufügen',
    'profile.recentTransactions': 'Letzte Transaktionen',
    'profile.progress': 'Fortschritt',
    'profile.items': 'Artikel',
    'profile.emptyWishlist': 'Ihre Wunschliste ist leer',
    'profile.browseCourses': 'Kurse durchsuchen',
    'profile.buy': 'Kaufen',
    'profile.earnedOn': 'Erhalten am',
    'profile.profileUpdated': 'Profil erfolgreich aktualisiert!',
    'profile.fundsAdded': 'zu Ihrer Geldbörse hinzugefügt!',
    'profile.removedFromWishlist': 'Von Wunschliste entfernt',
    
    // Checkout
    'checkout.title': 'Kasse',
    'checkout.orderSummary': 'Bestellübersicht',
    'checkout.paymentMethod': 'Zahlungsmethode',
    'checkout.wallet': 'Geldbörse',
    'checkout.instapay': 'InstaPay',
    'checkout.vodafone': 'Vodafone Cash',
    'checkout.confirmPayment': 'Zahlung bestätigen',
    'checkout.transactionRef': 'Transaktionsreferenz',
    'checkout.copyNumber': 'Nummer kopieren',
    'checkout.total': 'Gesamt',
    'checkout.choosePayment': 'Wählen Sie eine Zahlungsmethode, um Ihre Bestellung abzuschließen.',
    'checkout.back': 'Zurück',
    'checkout.price': 'Preis',
    'checkout.discount': 'Rabatt',
    'checkout.securePayment': '100% sichere verschlüsselte Zahlung',
    'checkout.availableBalance': 'Verfügbares Guthaben',
    'checkout.insufficientBalance': 'Unzureichendes Guthaben',
    'checkout.instantTransfer': 'Sofortüberweisung',
    'checkout.mobileWallet': 'Mobile Geldbörse',
    'checkout.instapaySteps': 'InstaPay-Schritte:',
    'checkout.vodafoneSteps': 'Vodafone Cash-Schritte:',
    'checkout.openBankApp': 'Öffnen Sie Ihre Banking-App',
    'checkout.chooseInstapay': 'Wählen Sie InstaPay-Überweisung',
    'checkout.enterAccount': 'Geben Sie dieses Konto ein:',
    'checkout.openVodafone': 'Öffnen Sie Vodafone Cash',
    'checkout.chooseSendMoney': 'Wählen Sie Geld senden',
    'checkout.enterNumber': 'Geben Sie diese Nummer ein:',
    'checkout.enterAmount': 'Betrag eingeben:',
    'checkout.enterRefAfter': 'Geben Sie die Referenz nach der Überweisung ein',
    'checkout.paymentSuccessful': 'Zahlung erfolgreich!',
    'checkout.amountDeducted': 'Der Betrag wurde von Ihrer Geldbörse abgezogen.',
    'checkout.topUpOrChoose': 'Bitte laden Sie Ihre Geldbörse auf oder wählen Sie eine andere Zahlungsmethode.',
    'checkout.refRequired': 'Transaktionsreferenz erforderlich',
    'checkout.enterRefVerify': 'Bitte geben Sie eine Transaktionsreferenz zur Verifizierung ein.',
    'checkout.requestSubmitted': 'Anfrage übermittelt!',
    'checkout.accessActivated': 'Ihr Zugang wird innerhalb von 24 Stunden nach Zahlungsbestätigung aktiviert.',
    'checkout.copied': 'Kopiert!',
    'checkout.copiedInstapay': 'InstaPay-Konto kopiert',
    'checkout.copiedVodafone': 'Vodafone Cash-Nummer kopiert',
    'checkout.newBalance': 'Neues Guthaben',
    'checkout.afterPurchase': 'Nach dem Kauf',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Ansehen',
    'common.buy': 'Kaufen',
    'common.free': 'Kostenlos',
    'common.all': 'Alle',
    'common.webDevelopment': 'Webentwicklung',
    'common.design': 'Design',
    'common.cms': 'CMS',
    'common.returnHome': 'Zur Startseite zurückkehren',
    'common.pageNotFound': 'Seite nicht gefunden',
    'common.oops': 'Hoppla!',
    'common.responsiveDesign': 'Responsives Design',
    'common.seoOptimized': 'SEO-optimiert',
    'common.fastLoading': 'Schnelle Ladezeit',
    'common.modernUiux': 'Modernes UI/UX',
    'common.crossBrowser': 'Browser-kompatibel',
    'common.mobileFirst': 'Mobile-First-Ansatz',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
